### ISSUE TITLE
Typing svg has a new url

### ISSUE THREAD

**Issue by DenverCoder1** [MainakRepositor/MainakRepositor#2]
Hi,

I'm glad you are enjoying my typing svg animation code which you have on your profile!

I have now made it into a public repository and it has a new url.

The old link will be going away, so you will need to update your link to the new url.

Link to repo: https://github.com/DenverCoder1/readme-typing-svg

Thanks :smiley:

**Comment by MainakRepositor** [comment]
Thank you for the information. I will do the needful 😊
